### PR TITLE
[WIP] Port to Apache Cordova

### LINKED ISSUE #16: Migration to Apache Cordova
I'd like to suggest that we migrate from Adobe PhoneGap to Apache Cordova as our app compiler.  While PhoneGap was based on Cordova technology, when the projects split Cordova became much more powerful as an open-source tool, and it has several benefits: 

- Better compilation, offline in the terminal (no more uploads and compressing)
- More supported FOSS community
- Easier plugin integration

I'd like this to begin as soon as possible, as it's critical to testing future versions of SC4.

### PR DESCRIPTION
**Pull request by locness3**
I think I got the thing ported to Cordova, at least browser runs fine.

@micahlt and anyone willing to, are you able to [set up your dev env for android](https://cordova.apache.org/docs/en/latest/guide/platforms/android/) and build the app? If yes, does it work and looks good?

Also, I think we should update the package.json scripts.

fixes #16

### CODE REVIEW

**Comment by locness3** [comment]
I was able to build the app and run it on the official emulator (using the absolutely shitty apkonline.net because i don't have a device at hand and my PC can't run the emulator :/) Had the problem with stuff loaded from ˋ/ˋ but didn't bother fixing it, i think it would work anyways. Also the app doesn't have an icon, I'll look into this.

If you want to build it yourself, set up your environement according to [this guide](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html), then do ˋcordova platform add android`, ˋnpm run build`, remove the slashes in the references to the CSS and JS files, and then do ˋcordova build` to get an APK.

**Comment by locness3** [comment]
Also, I switched to a more "honest" version number, provided we follow semver - `0.0.6`; is that OK?

pinging @micahlt once again, but it seems he's dead - once again any help's appreciated @Scratch-Client-4/everyone

**Comment by micahlt** [comment]
@locness3 Not dead, just returning from vacation.  Thanks for working on this.  Yeah, thanks for the more accurate versioning.  😄 Closing this issue.

**Comment by githubfan** [comment]
@micahlt could you also encourage people to join the discord? although I know you can't join it yourself

https://discord.gg/TUBUD4D

**Comment by locness3** [comment]
Also, I solved the "slashes" problem using the following parcel build command :
```
parcel build index.html --global index --public-url .
```

**Comment by micahlt** [comment]
This is working for me- merging now!

**Pull request merged**
